# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-11 13:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0005_auto_20200110_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='result_proof',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
